### ISSUE TITLE
class "Hachther\Mesomb\Helper\HasPayments" not found

### ISSUE THREAD

**Issue by Stephan-MC** [hachther/laravel-mesomb#2]
i just downloaded laravel  mesomb and got the error in the image below whenever i run my app.

Je viens d'installer laravel mesomb et je tombe toujours sur cette erreur apres l'installation

![image](https://github.com/hachther/laravel-mesomb/assets/77833621/0a06ad03-3df1-476b-811b-847d4ef950ed)

voici mon Order.php ou jai essayer d'ajouter le "Trait"
![image](https://github.com/hachther/laravel-mesomb/assets/77833621/6e5725ce-1dae-4cba-b16f-449f719ac6d3)

**Comment by hachther** [comment]
Hello,

HasPayments is a trait, not an interface so you cannot use it with "implements". Use it with "use HasPayments" instruction.
